# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

tasks:
  default:
    silent: true
    cmds:
      - task --list-all --color

  prec:
    desc: Install dependencies (only if manifests changed)
    preconditions:
      - test -f $(which npm)
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      - npm install

  export:
    desc: Build PDF from markdown
    deps:
      - prec
    cmds:
      - npm run export

  build:
    desc: Build static site into dist/
    deps:
      - prec
    cmds:
      - npm run build

  dev:
    desc: Run development
    deps:
      - prec
    cmds:
      - npm run dev

  clean:
    desc: Clean all artifacts
    cmds:
      - rm -rf node_modules/ dist/
